---
- name: Cleanup OpenStack's security group entities
  hosts: localhost
  gather_facts: no

  tasks:
  - name: Delete empty ICMP rule
    openstack.cloud.security_group_rule:
      cloud: "{{ cloud }}"
      security_group: "{{ secgroup_name }}"
      state: absent
      protocol: icmp
      remote_ip_prefix: 0.0.0.0/0

  - name: Delete -1 ICMP rule
    openstack.cloud.security_group_rule:
      cloud: "{{ cloud }}"
      security_group: "{{ secgroup_name }}"
      state: absent
      protocol: icmp
      port_range_min: -1
      port_range_max: -1
      remote_ip_prefix: 0.0.0.0/0

  - name: Delete empty UDP rule
    openstack.cloud.security_group_rule:
      cloud: "{{ cloud }}"
      security_group: "{{ secgroup_name }}"
      state: absent
      protocol: udp
      remote_ip_prefix: 0.0.0.0/0

  # Skip individual TCP rule deletions since they cause "multiple matches" errors
  # The security group deletion will cascade and delete all remaining rules
  
  - name: Delete security group (cascades to delete remaining TCP rules)
    openstack.cloud.security_group:
      cloud: "{{ cloud }}"
      name: "{{ secgroup_name }}"
      state: absent
